//IGAL WINICKI 251512 - NICOLAS STAROVIESCHIK 270315
package interfaz;

import dominio.Deposito;
import static java.lang.Integer.parseInt;
import dominio.*;
import java.util.*;
import javax.swing.JOptionPane;

public class IngresoDeposito extends javax.swing.JFrame implements Observer {

    private Sistema modelo;

    public IngresoDeposito() {
        initComponents();
        txtNumero.setText("");
        txtTamaño.setText("");

    }

    public IngresoDeposito(Sistema unSistema) {
        modelo = unSistema;

        initComponents();
        cargarListaDeposito();
        modelo.addObserver(this);
    }

    public void cargarListaDeposito() {
        lstDeposito.setListData(modelo.getListaDepositos().toArray());
    }

    public boolean estaNumeroDeposito(int num) {
        boolean esta = false;
        ArrayList<Deposito> listaDepositos = modelo.getListaDepositos();
        Iterator<Deposito> it = listaDepositos.iterator();
        while (it.hasNext()) {
            Deposito dep = it.next();
            if (dep.getNumeroDeIdentificacion() == num) {
                esta = true;
            }
        }
        return esta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTamaño = new javax.swing.JTextField();
        rdoCEstantes = new javax.swing.JRadioButton();
        rdoSEstantes = new javax.swing.JRadioButton();
        rdoRefrigerado = new javax.swing.JRadioButton();
        rdoNRefrigerado = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstDeposito = new javax.swing.JList();
        btnSalir = new javax.swing.JButton();
        btnAgregar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ingreso Depositos");

        jLabel1.setText("Número");

        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });

        jLabel2.setText("Tamaño");

        txtTamaño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTamañoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoCEstantes);
        rdoCEstantes.setText("Con Estantes ");
        rdoCEstantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoCEstantesActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoSEstantes);
        rdoSEstantes.setText("Sin Estantes ");
        rdoSEstantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoSEstantesActionPerformed(evt);
            }
        });

        buttonGroup2.add(rdoRefrigerado);
        rdoRefrigerado.setText("Refrigerado");
        rdoRefrigerado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoRefrigeradoActionPerformed(evt);
            }
        });

        buttonGroup2.add(rdoNRefrigerado);
        rdoNRefrigerado.setText("No Refrigerado");
        rdoNRefrigerado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNRefrigeradoActionPerformed(evt);
            }
        });

        jLabel3.setText("Estantes");

        jLabel4.setText("Refrigeración");

        lstDeposito.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstDeposito);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnAgregar1.setText("Agregar");
        btnAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rdoSEstantes)
                                    .addComponent(rdoNRefrigerado)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTamaño)
                                    .addComponent(txtNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdoCEstantes)
                            .addComponent(rdoRefrigerado))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addComponent(btnAgregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(503, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdoSEstantes)
                        .addComponent(rdoCEstantes)))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rdoRefrigerado)
                    .addComponent(rdoNRefrigerado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(230, Short.MAX_VALUE)
                    .addComponent(btnAgregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdoCEstantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoCEstantesActionPerformed

    }//GEN-LAST:event_rdoCEstantesActionPerformed

    private void rdoSEstantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoSEstantesActionPerformed
    }//GEN-LAST:event_rdoSEstantesActionPerformed

    private void rdoRefrigeradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoRefrigeradoActionPerformed
    }//GEN-LAST:event_rdoRefrigeradoActionPerformed

    private void rdoNRefrigeradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNRefrigeradoActionPerformed
    }//GEN-LAST:event_rdoNRefrigeradoActionPerformed

    private void btnAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar1ActionPerformed
        int numero;
        int tamaño;
        try {

            numero = Integer.parseInt(txtNumero.getText());
            if (estaNumeroDeposito(numero)) {
                JOptionPane.showMessageDialog(null, "No se puede repetir el numero de identificacion", "Error", 0);
            } else {
                if (numero <= 0) {
                    JOptionPane.showMessageDialog(null, "El numero de identificacion debe ser mayor a 0", "Error", 0);
                } else {

                    tamaño = Integer.parseInt(txtTamaño.getText());
                    if (!rdoCEstantes.isSelected() && !rdoSEstantes.isSelected()) {
                        JOptionPane.showMessageDialog(null, "Rellene todos los campos correctamente", "Error", 0);
                    } else {
                        if (tamaño <= 0) {
                            JOptionPane.showMessageDialog(null, "El tamaño ingresado debe ser mayor a 0", "Error", 0);
                        } else {

                            if (!rdoRefrigerado.isSelected() && !rdoNRefrigerado.isSelected()) {
                                JOptionPane.showMessageDialog(null, "Rellene todos los campos correctamente", "Error", 0);
                            } else {
                                boolean estantes = rdoCEstantes.isSelected();
                                boolean refrigerante = rdoRefrigerado.isSelected();

                                Deposito d1 = new Deposito(numero, tamaño, estantes, refrigerante);

                                modelo.agregarDeposito(d1);
                                cargarListaDeposito();
                                txtNumero.setText("");
                                txtTamaño.setText("");
                            }
                        }
                    }
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Rellene todos los campos correctamente", "Error", 0);
        }
        
        


    }//GEN-LAST:event_btnAgregar1ActionPerformed

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void txtTamañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTamañoActionPerformed
    }//GEN-LAST:event_txtTamañoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar1;
    private javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstDeposito;
    private javax.swing.JRadioButton rdoCEstantes;
    private javax.swing.JRadioButton rdoNRefrigerado;
    private javax.swing.JRadioButton rdoRefrigerado;
    private javax.swing.JRadioButton rdoSEstantes;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtTamaño;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {

    }
}
